(deftheme my-spacemacs-wombat
  "Created 2016-07-13.")

(custom-theme-set-faces
 'my-spacemacs-wombat
 '(cursor ((t (:foreground "#DCDCCC" :background "SkyBlue2"))))
 '(mouse ((t (:foreground "white"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#ddaa6f"))))
 '(minibuffer-prompt ((t (:foreground "#e5786d"))))
 '(highlight ((t (:underline (:color foreground-color :style line) :foreground "#ffffff" :background "#454545"))))
 '(region ((t (:foreground "#f6f3e8" :background "#444444"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:foreground "#f6f3e8" :background "#333366"))))
 '(trailing-whitespace ((t (:background "#99968b"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#e5786d"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#6C8C6C" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#99968b"))))
 '(font-lock-constant-face ((t (:foreground "#e5786d"))))
 '(font-lock-doc-face ((t (:foreground "#ddaa6f" :inherit nil))))
 '(font-lock-function-name-face ((t (:foreground "#30afd7"))))
 '(font-lock-keyword-face ((t (:foreground "#88fff2" :weight normal))))
 '(font-lock-negation-char-face ((t (:weight bold :foreground "#FDECBC"))))
 '(font-lock-preprocessor-face ((t (:foreground "#ddaa6f"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#8CAC8C"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#FDECBC"))))
 '(font-lock-string-face ((t (:foreground "#55e074"))))
 '(font-lock-type-face ((t (:weight bold :foreground "#92a05e"))))
 '(font-lock-variable-name-face ((t (:foreground "#ffff74"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#ccaa8f"))))
 '(button ((t (:underline (:color foreground-color :style line) :inherit (link)))))
 '(link ((t (:weight bold :underline (:color foreground-color :style line) :foreground "#8ac6f2"))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#e5786d"))))
 '(fringe ((t (:foreground "#DCDCCC" :background "#303030"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#e7f6da" :background "#303030"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#ffffff" :background "#606060"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#d8e474"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#857b6f" :background "#3e3e3e"))))
 '(isearch ((t (:weight bold :foreground "#857b6f" :background "#343434"))))
 '(isearch-fail ((t (:foreground "#DCDCCC" :background "#996060"))))
 '(lazy-highlight ((t (:weight bold :foreground "#a0a8b0" :background "#384048"))))
 '(match ((t (:weight bold :foreground "#ECBC9C" :background "#202020"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(default ((t (:family "Source Code Pro" :foundry "adobe" :width normal :height 98 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#f6f3e8" :background "#313131" :stipple nil :inherit nil)))))

(provide-theme 'my-spacemacs-wombat)
