(deftheme my-wombat
  "Created 2015-04-21.")

(custom-theme-set-variables
 'my-wombat
 '(ansi-color-names-vector ["#242424" "#e5786d" "#95e454" "#cae682" "#8ac6f2" "magenta3" "cyan3" "gray90"]))

(custom-theme-set-faces
 'my-wombat
 '(cursor ((((class color) (min-colors 89)) (:background "#656565"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#303030"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#454545" :foreground "#ffffff" :underline t))))
 '(region ((((class color) (min-colors 89)) (:background "#444444" :foreground "#f6f3e8"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#333366" :foreground "#f6f3e8"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#343434" :foreground "#857b6f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#384048" :foreground "#a0a8b0"))))
 '(mode-line ((t (:background "#606060" :foreground "#ffffff"))))
 '(mode-line-inactive ((t (:background "#3e3e3e" :foreground "#857b6f"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight bold))))
 '(font-lock-builtin-face ((t (:foreground "#e5786d"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(font-lock-constant-face ((t (:foreground "#e5786d"))))
 '(font-lock-function-name-face ((t (:foreground "#30afd7"))))
 '(font-lock-keyword-face ((t (:foreground "#88fff2" :weight bold))))
 '(font-lock-string-face ((t (:foreground "#55e074"))))
 '(font-lock-type-face ((t (:foreground "#92a05e" :weight bold))))
 '(font-lock-variable-name-face ((t (:foreground "#ffff74"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline t))))
 '(button ((t (:inherit link))))
 '(header-line ((((class color) (min-colors 89)) (:background "#303030" :foreground "#e7f6da"))))
 '(font-lock-backslash-escaped-char-face ((t (:inherit (bold)))))
 '(font-lock-backslash-face ((t (:inherit (bold)))))
 '(font-lock-format-specier-face ((t (:inherit (bold)))))
 '(font-lock-format-specier-code-face ((t (:inherit (bold)))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-doc-face ((t (:inherit nil :foreground "#ddaa6f"))))
 '(mode-line-buffer-id ((t (:foreground "#d8e474" :weight bold))))
 '(font-lock-preprocessor-face ((t (:foreground "#ddaa6f"))))
 '(font-lock-doc-markup-face ((t (:inherit font-lock-keyword-face))))
 '(font-lock-doc-string-face ((t (:inherit font-lock-doc-face))))
 '(font-lock-label-face ((t (:inherit font-lock-type-face))))
 '(ediff-current-diff-A ((t (:background "#553333"))))
 '(ediff-current-diff-B ((t (:inherit ediff-current-diff-A))))
 '(ediff-current-diff-C ((t (:inherit ediff-current-diff-A))))
 '(ediff-current-diff-Ancestor ((t (:inherit ediff-current-diff-A))))
 '(ediff-even-diff-Ancestor ((t (:inherit ediff-even-diff-A))))
 '(ediff-even-diff-A ((t (:background "light grey" :foreground "Black"))))
 '(ediff-even-diff-B ((t (:inherit ediff-even-diff-A))))
 '(ediff-even-diff-C ((t (:inherit ediff-even-diff-A))))
 '(ediff-fine-diff-Ancestor ((t (:inherit ediff-fine-diff-A))))
 '(ediff-fine-diff-A ((((class color) (min-colors 88) (background light)) (:background "#ffbbbb")) (((class color) (min-colors 88) (background dark)) (:background "#aa2222")) (((class color) (min-colors 16)) (:background "sky blue" :foreground "Navy")) (((class color)) (:weight bold :background "sky blue" :foreground "white")) (t (:stipple "gray3" :underline (:color foreground-color :style line)))))
 '(ediff-fine-diff-B ((t (:inherit ediff-fine-diff-A))))
 '(ediff-fine-diff-C ((t (:inherit ediff-fine-diff-A))))
 '(ediff-odd-diff-Ancestor ((t (:inherit ediff-odd-diff-A))))
 '(ediff-odd-diff-A ((t (:background "Grey" :foreground "White"))))
 '(ediff-odd-diff-B ((t (:inherit ediff-odd-diff-A))))
 '(ediff-odd-diff-C ((t (:inherit ediff-odd-diff-A))))
 '(default ((t (:foreground "#f6f3e8")))))

(provide-theme 'my-wombat)
